"""应用版本和本地资源限制的集中配置。"""

APP_NAME = "Quant Research Workbench"
APP_VERSION = "0.2.0"

SINGLE_FILE_MAX_MB = 20
COMPARISON_FILE_MAX_MB = 20
MAX_ROWS_PER_FILE = 200_000
MAX_COLUMNS_PER_FILE = 500
MAX_COMPARISON_FILES = 6
